image:
  name: "registry.git.equinor.com/sdp/nrlib/nrlib:1.2.5"

variables:
  GIT_STRATEGY:   "fetch"
  HTTP_PROXY:     "http://www-proxy.statoil.no:80"
  HTTPS_PROXY:    "http://www-proxy.statoil.no:80"
  FTP_PROXY:      "http://www-proxy.statoil.no:80"
  NO_PROXY:       "git.equinor.com"
  CODE_DIR:       "$CI_PROJECT_DIR"
  ARTIFACTS:      "$CODE_DIR/artifacts"
  MAKE:           "make"
  BASE_DIST:      "dist"
  WORKON_HOME:    "${CODE_DIR}/.venv"
  RMS10_PATH:     "/prog/roxar/rms/versions/10.1.3/linux-amd64-gcc_4_4-release/bin"
  SDP361_PATH:    "/prog/sdpsoft/python3.6.1/bin"
  SHELL:          "/bin/bash"
  VIRTUAL_PYTHON: "${WORKON_HOME}/bin/python"

stages:
  - check requirements
  - build
  - testing
  - deploy
  - clean

before_script:
  - 'eval export PATH=/root/.local/bin:$PATH'

security check:
  stage: check requirements
  variables:
    PYTHON: "$SDP361_PATH/python3"
    USE_SITE_PACKAGES: "no"
  script:
    - 'eval export PATH=$SDP361_PATH:$PATH'
    - 'eval $MAKE check-requirements'
  allow_failure: true  # The dependencies are not easily updatable

# TODO: Fix...
test:SDPsoft (3.6.1):
  stage: testing  # https://github.com/ksator/continuous-integration-with-python
  variables:
    DISTRIBUTION_DIR: $BASE_DIST/nrlib-python3.6.1
    PYTHON: "$SDP361_PATH/python3"
  script:
    - 'eval export PATH=$SDP361_PATH:$PATH'
    - 'eval $MAKE install-pipenv'
    - 'eval $MAKE install-wheel'
    - 'eval $MAKE install-requirements'
    - 'eval $MAKE tests'
  dependencies:
    - build:SDPsoft (3.6.1)

test:RMS 10.1.3 (3.4.2):
  stage: testing  # https://github.com/ksator/continuous-integration-with-python
  variables:
    DISTRIBUTION_DIR: $BASE_DIST/nrlib-RMS-10.1.3
    ROXENV: "$RMS10_PATH/roxenv"
    PYTHON: "$RMS10_PATH/python"
    USE_SKIP_LOCKING: "yes"
  script:
    - 'eval $ROXENV $MAKE install-wheel'
    - 'eval $ROXENV $MAKE install-requirements'
    - 'eval $ROXENV $MAKE tests'
  dependencies:
    - build:RMS 10.1.3 (3.4.2)

build:RMS 10.1.3 (3.4.2):
  stage: build
  variables:
    DISTRIBUTION_DIR: $BASE_DIST/nrlib-RMS-10.1.3
    ROXENV: "$RMS10_PATH/roxenv"
    PYTHON: "$RMS10_PATH/python"
    USE_SKIP_LOCKING: "yes"
  script:
    - 'eval export LD_LIBRARY_PATH="/prog/roxar/rms/versions/10.1.3/linux-amd64-gcc_4_4-release/lib:$LD_LIBRARY_PATH"'
    - 'eval export LIBRARY_PATH="/prog/roxar/rms/versions/10.1.3/linux-amd64-gcc_4_4-release/lib:$LIBRARY_PATH"'
    - 'eval export PATH="$RMS10_PATH:$PATH"'
    - 'eval $MAKE build-wheel'
  artifacts:
    expire_in: 1 week
    paths:
      - '$DISTRIBUTION_DIR'

build:SDPsoft (3.6.1):
  stage: build
  variables:
    DISTRIBUTION_DIR: $BASE_DIST/nrlib-python3.6.1
    PYTHON: "$SDP361_PATH/python3"
  script:
    - 'eval export PATH="$SDP361_PATH:$PATH"'
    - 'eval $MAKE build-wheel'
  artifacts:
    expire_in: 1 week
    paths:
      - '$DISTRIBUTION_DIR'

deploy release candidate:
  stage: deploy
  script:
    - ""  # TODO
  only:
   - master
  dependencies:
    - build:RMS 10.1.3 (3.4.2)
    - build:SDPsoft (3.6.1)
  artifacts:
    paths:
      - '$BASE_DIST'

cleanup:
  stage: clean
  script:
    - 'eval $MAKE clean'
  when: always
