image:
  name: "git.statoil.no:4567/sdp/nrlib/nrlib:1.1.1"

variables:
  GIT_STRATEGY: "fetch"
  HTTP_PROXY:   "http://www-proxy.statoil.no:80"
  HTTPS_PROXY:  "http://www-proxy.statoil.no:80"
  FTP_PROXY:    "http://www-proxy.statoil.no:80"
  NO_PROXY:     "git.statoil.no"
  CODE_DIR:     "$CI_PROJECT_DIR"
  ARTIFACTS:    "$CODE_DIR/artifacts"
  MAKE:         "make"
  RUN:          "/bin/bash -c"
  BASE_DIST:    "dist"

stages:
  - check requirements
  - build
  - testing
  - deploy

test:SDPsoft (3.6.1):
  stage: testing  # https://github.com/ksator/continuous-integration-with-python
  variables:
    DISTRIBUTION_DIR: $BASE_DIST/nrlib-python3.6.1
    PYTHON: "/prog/sdpsoft/python3.6.1/bin/python3"
  script:
    - 'eval $MAKE install'
    - 'eval $MAKE tests'
  dependencies:
    - build:SDPsoft (3.6.1)

test:RMS 10.1.1 (3.4.2):
  stage: testing  # https://github.com/ksator/continuous-integration-with-python
  variables:
    DISTRIBUTION_DIR: $BASE_DIST/nrlib-RMS-10.1.1
    ROXENV: "/prog/roxar/rms/versions/10.1.1/linux-amd64-gcc_4_4-release/bin/roxenv"
    PYTHON: "/prog/roxar/rms/versions/10.1.1/linux-amd64-gcc_4_4-release/bin/python"
  script:
    - 'eval $ROXENV $MAKE install'
    - 'eval $ROXENV $MAKE tests'
  dependencies:
    - build:RMS 10.1.1 (3.4.2)

build:RMS 10.1.1 (3.4.2):
  stage: build
  variables:
    DISTRIBUTION_DIR: $BASE_DIST/nrlib-RMS-10.1.1
    ROXENV: "/prog/roxar/rms/versions/10.1.1/linux-amd64-gcc_4_4-release/bin/roxenv"
    PYTHON: "/prog/roxar/rms/versions/10.1.1/linux-amd64-gcc_4_4-release/bin/python"
  script:
    - 'eval $ROXENV $MAKE build'
  artifacts:
    expire_in: 1 week
    paths:
      - '$DISTRIBUTION_DIR'

build:SDPsoft (3.6.1):
  stage: build
  variables:
    DISTRIBUTION_DIR: $BASE_DIST/nrlib-python3.6.1
    PYTHON: "/prog/sdpsoft/python3.6.1/bin/python3"
  script:
    - 'eval $MAKE build'
  artifacts:
    expire_in: 1 week
    paths:
      - '$DISTRIBUTION_DIR'

deploy release candidate:
  stage: deploy
  script:
    - ""  # TODO
  only:
   - master
  dependencies:
    - build:RMS 10.1.1 (3.4.2)
    - build:SDPsoft (3.6.1)
  artifacts:
    paths:
      - '$BASE_DIST'
