services:
  build-linux:
    image: quay.io/pypa/manylinux2014_x86_64
    environment:
      PYTHON:
      NRLIB_LINKING: "${NRLIB_LINKING-static}"
    volumes:
      # Sharing the entire volume causes the created venv to be broken on the host
      - "./Makefile:/code/Makefile"
      - "./bin:/code/bin"
      - "./src:/code/src"
      - "./gaussianfft:/code/gaussianfft"
      - "./setup.py:/code/setup.py"

      - "./LOWEST_SUPPORTED_PYTHON_VERSION.txt:/code/LOWEST_SUPPORTED_PYTHON_VERSION.txt"
      - "./LICENSE.txt:/code/LICENSE.txt"
      - "./README:/code/README"

      - "./wheelhouse:/code/wheelhouse"  # This is where the build artefacts are placed
    entrypoint: ["make", "-C", "/code", "build"]
