services:
  build-linux:
    image: quay.io/pypa/manylinux2014_x86_64
    environment:
      PYTHON:
    # Sharing the entire volume causes the created venv to be broken on the host
    volumes:
      # These files are used for building the extension
      - "./CMakeLists.txt:/code/CMakeLists.txt"
      - "./Makefile:/code/Makefile"
      - "./bin:/code/bin"
      - "./cmake:/code/cmake"
      - "./gaussianfft:/code/gaussianfft"
      - "./pyproject.toml:/code/pyproject.toml"
      - "./sources:/code/sources"
      - "./src:/code/src"
      - "./utils.py:/code/utils.py"

      # These are included in the source distribution
      - "./LICENSE.txt:/code/LICENSE.txt"
      - "./README.md:/code/README.md"
      - "./py.typed:/code/py.typed"

      - "./wheelhouse:/code/wheelhouse"  # This is where the build artefacts are placed
    entrypoint: ["make", "-C", "/code", "build"]
